version: '3.3'
services:
  db:
    build: ./db/MYSQL
    #restart: always
    env_file:
      - ./db/MYSQL/mysql.env
    container_name: db_mysql
    environment:
      - TZ=Asia/Seoul
    ports:
      # 로컬:컨테이너
      - '3333:3306'
    volumes:
      - ./db/MYSQL/res/data/:/var/lib/mysql

  backend_spring:
    build: ./backend
    env_file:
      - ./backend/backend.env
    container_name: backend_spring
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/srv/docker-server
    command: java -jar /srv/docker-server/build/libs/backend-0.0.1-SNAPSHOT.jar

  backend_signaling_server:
    build: ./backend_chatting
    container_name: backend_signaling_server
    ports:
      - '8000:8000'
    volumes:
      - ./backend_chatting:/srv/docker-server

  front_node:
    build: ./front
    container_name: front_node
    ports:
      - '3000:3000'
    volumes:
      - ./front:/srv/docker-server